import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primary,
            width: 2.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 6,
        space: 6,
        color: appTheme.black900,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black90001,
          fontSize: 16.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 13.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray400,
          fontSize: 10.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.lightBlue800,
          fontSize: 37.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w700,
        ),
        headlineMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 28.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w600,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black90001,
          fontSize: 24.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w600,
        ),
        labelLarge: TextStyle(
          color: appTheme.greenA700,
          fontSize: 12.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 20.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 18.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: colorScheme.primary,
          fontSize: 14.fSize,
          fontFamily: 'Lexend',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF0075C3),
    primaryContainer: Color(0XFF111827),
    secondary: Color(0XFF111827),
    secondaryContainer: Color(0XFF3D5BF6),
    tertiary: Color(0XFF111827),
    tertiaryContainer: Color(0XFF3D5BF6),

    // Background colors
    background: Color(0XFF111827),

    // Surface colors
    surface: Color(0XFF111827),
    surfaceTint: Color(0XFF111827),
    surfaceVariant: Color(0XFF3D5BF6),

    // Error colors
    error: Color(0XFF111827),
    errorContainer: Color(0XFF3D5BF6),
    onError: Color(0XFF9A9A9A),
    onErrorContainer: Color(0XFF111827),

    // On colors(text colors)
    onBackground: Color(0XFF9A9A9A),
    onInverseSurface: Color(0XFF9A9A9A),
    onPrimary: Color(0XFF111827),
    onPrimaryContainer: Color(0XFF9A9A9A),
    onSecondary: Color(0XFF9A9A9A),
    onSecondaryContainer: Color(0XFF111827),
    onTertiary: Color(0XFF9A9A9A),
    onTertiaryContainer: Color(0XFF111827),

    // Other colors
    outline: Color(0XFF111827),
    outlineVariant: Color(0XFF111827),
    scrim: Color(0XFF111827),
    shadow: Color(0XFF111827),

    // Inverse colors
    inversePrimary: Color(0XFF111827),
    inverseSurface: Color(0XFF111827),

    // Pending colors
    onSurface: Color(0XFF9A9A9A),
    onSurfaceVariant: Color(0XFF111827),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFBBC04);

  // Black
  Color get black900 => Color(0XFF020202);
  Color get black90001 => Color(0XFF000000);

  // Blue
  Color get blue300 => Color(0XFF5CBEFF);
  Color get blue400 => Color(0XFF4D9FEA);

  // BlueGrayDa
  Color get blueGray100Da => Color(0XDAD1D3D9);

  // BlueGray
  Color get blueGray200 => Color(0XFFADB3BC);
  Color get blueGray20001 => Color(0XFFAAADB7);
  Color get blueGray400 => Color(0XFF8C8C8C);
  Color get blueGray40001 => Color(0XFF898A8D);
  Color get blueGray40002 => Color(0XFF888888);
  Color get blueGray600 => Color(0XFF596D87);
  Color get blueGray60001 => Color(0XFF5A6D77);
  Color get blueGray700 => Color(0XFF455A64);

  // BlueGrayf
  Color get blueGray3007f => Color(0X7FA3A9B3);

  // Cyan
  Color get cyan50 => Color(0XFFE7FFF3);

  // Gray
  Color get gray200 => Color(0XFFE8EAEC);
  Color get gray20001 => Color(0XFFE7E7E7);
  Color get gray300 => Color(0XFFE0E2E6);
  Color get gray30001 => Color(0XFFDEDEDE);
  Color get gray400 => Color(0XFFC2C6CC);
  Color get gray500 => Color(0XFF9E9E9E);
  Color get gray600 => Color(0XFF7D7D7D);
  Color get gray800 => Color(0XFF484848);
  Color get gray900 => Color(0XFF182034);

  // Grayb
  Color get gray8005b => Color(0X5B3C3C43);

  // Green
  Color get greenA700 => Color(0XFF00BF63);

  // Indigo
  Color get indigo200 => Color(0XFF87B3D1);

  // LightBlue
  Color get lightBlue800 => Color(0XFF0068C9);

  // Orange
  Color get orange300 => Color(0XFFFFBB56);

  // Red
  Color get red500 => Color(0XFFFF3C2B);
  Color get red50001 => Color(0XFFEA4335);
  Color get redA700 => Color(0XFFED0006);

  // Teal
  Color get teal300 => Color(0XFF41C796);
  Color get teal50 => Color(0XFFE7F8F2);
  Color get teal900 => Color(0XFF004423);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
  Color get whiteA70001 => Color(0XFFFCFCFE);

  // Yellow
  Color get yellow50 => Color(0XFFFFF8E7);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
