import '../ratings_two_screen/widgets/userprofile2_item_widget.dart';import 'package:ahmed_s_application3/core/app_export.dart';import 'package:ahmed_s_application3/widgets/app_bar/appbar_image.dart';import 'package:ahmed_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:ahmed_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:ahmed_s_application3/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class RatingsTwoScreen extends StatelessWidget {const RatingsTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(leadingWidth: 42.h, leading: AppbarImage(svgPath: ImageConstant.imgAngleleft, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapAngleleftone(context);}), title: AppbarSubtitle(text: "lbl_ratings2".tr, margin: EdgeInsets.only(left: 93.h))), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 4.v), child: Column(children: [Container(margin: EdgeInsets.only(left: 5.h, right: 3.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.outlineBlack90001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgFrame10000036268, height: 92.v, width: 147.h, radius: BorderRadius.circular(8.h), margin: EdgeInsets.symmetric(vertical: 4.v)), Padding(padding: EdgeInsets.only(left: 12.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_dianko_se_hotel".tr, style: theme.textTheme.titleSmall), SizedBox(height: 7.v), Text("msg_4_guests_2_room".tr, style: CustomTextStyles.bodyMediumGray500), SizedBox(height: 4.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_total_price".tr, style: CustomTextStyles.bodyMediumGray50014), TextSpan(text: "lbl_100".tr, style: CustomTextStyles.bodyMediumPrimary)]), textAlign: TextAlign.left), SizedBox(height: 5.v), CustomElevatedButton(height: 26.v, width: 74.h, text: "lbl_finished".tr, buttonStyle: CustomButtonStyles.fillTeal, buttonTextStyle: CustomTextStyles.titleSmallTeal300)]))])), Padding(padding: EdgeInsets.only(left: 8.h, top: 31.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_reviews".tr, style: CustomTextStyles.titleMediumPrimarySemiBold16), Text("lbl_see_more2".tr, style: CustomTextStyles.bodyMediumPrimary14)])), Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h, top: 16.v), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: 4, itemBuilder: (context, index) {return Userprofile2ItemWidget();}))), SizedBox(height: 100.v), SizedBox(width: 116.h, child: Divider()), SizedBox(height: 9.v)])))); } 
/// Navigates to the checkInOneScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [Navigator] widget
/// to push the named route for the checkInOneScreen.
onTapAngleleftone(BuildContext context) { Navigator.pushNamed(context, AppRoutes.checkInOneScreen); } 
 }
