import 'package:ahmed_s_application3/core/app_export.dart';import 'package:ahmed_s_application3/widgets/custom_elevated_button.dart';import 'package:ahmed_s_application3/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class Frame1000003735Screen extends StatelessWidget {Frame1000003735Screen({Key? key}) : super(key: key);

TextEditingController fullNameController = TextEditingController();

TextEditingController emailController = TextEditingController();

TextEditingController passwordController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: 312.h, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_full_name".tr, style: CustomTextStyles.titleMediumGray900), SizedBox(height: 7.v), CustomTextFormField(controller: fullNameController, hintText: "lbl_canda_nashat".tr, hintStyle: CustomTextStyles.bodyMediumPrimary14, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 13.v, 8.h, 13.v), child: CustomImageView(svgPath: ImageConstant.imgUserPrimary)), prefixConstraints: BoxConstraints(maxHeight: 50.v), borderDecoration: TextFormFieldStyleHelper.outlinePrimaryTL8, filled: true, fillColor: appTheme.whiteA700), SizedBox(height: 10.v), Text("lbl_email".tr, style: CustomTextStyles.titleMediumGray900), SizedBox(height: 8.v), CustomTextFormField(controller: emailController, hintText: "msg_canda_nashat_gmail_com".tr, hintStyle: CustomTextStyles.bodyMediumPrimary14, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 13.v, 8.h, 13.v), child: CustomImageView(svgPath: ImageConstant.imgMail)), prefixConstraints: BoxConstraints(maxHeight: 50.v), borderDecoration: TextFormFieldStyleHelper.outlinePrimaryTL8, filled: true, fillColor: appTheme.whiteA700), SizedBox(height: 11.v), Text("lbl_password".tr, style: CustomTextStyles.titleMediumGray900), SizedBox(height: 7.v), CustomTextFormField(controller: passwordController, hintText: "lbl_antksa1526543".tr, hintStyle: CustomTextStyles.bodyMediumPrimary14, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 13.v, 8.h, 13.v), child: CustomImageView(svgPath: ImageConstant.imgLock)), prefixConstraints: BoxConstraints(maxHeight: 50.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 15.v, 21.h, 15.v), child: CustomImageView(svgPath: ImageConstant.imgReply)), suffixConstraints: BoxConstraints(maxHeight: 50.v), contentPadding: EdgeInsets.symmetric(vertical: 16.v), borderDecoration: TextFormFieldStyleHelper.outlinePrimaryTL8, filled: true, fillColor: appTheme.whiteA700), SizedBox(height: 11.v), Text("lbl_phone_number".tr, style: CustomTextStyles.titleMediumGray900), SizedBox(height: 7.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [CustomImageView(svgPath: ImageConstant.imgCall, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 2.v), child: Text("msg_60_232_1568_4654".tr, style: CustomTextStyles.bodyMediumPrimary14))])), SizedBox(height: 5.v)])), bottomNavigationBar: CustomElevatedButton(height: 50.v, text: "lbl_sign_up2".tr, buttonTextStyle: CustomTextStyles.titleLarge_1, onTap: () {onTapSignup(context);}))); } 
/// Navigates to the verifyFourScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [Navigator] widget
/// to push the named route for the verifyFourScreen.
onTapSignup(BuildContext context) { Navigator.pushNamed(context, AppRoutes.verifyFourScreen); } 
 }
